package com.toolbox.ddj.ui.theme

import androidx.compose.ui.graphics.Color

// KernelSU Style 色板：中性 Material 基调 + 叮咚鸡品牌橙作为 seed
val BrandSeed = Color(0xFFFF9800)
val BrandYellow = Color(0xFFFFC107)

val LightPrimary = Color(0xFF8B5000)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDDB3)
val LightOnPrimaryContainer = Color(0xFF2C1600)
val LightSecondary = Color(0xFF705B41)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFBDEBC)
val LightOnSecondaryContainer = Color(0xFF271904)
val LightTertiary = Color(0xFF53643E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD6E9B9)
val LightOnTertiaryContainer = Color(0xFF121F03)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFF8F4)
val LightOnBackground = Color(0xFF211A13)
val LightSurface = Color(0xFFFFF8F4)
val LightOnSurface = Color(0xFF211A13)
val LightSurfaceVariant = Color(0xFFF1E0D0)
val LightOnSurfaceVariant = Color(0xFF50453A)
val LightOutline = Color(0xFF827568)

val DarkPrimary = Color(0xFFFFB869)
val DarkOnPrimary = Color(0xFF4A2800)
val DarkPrimaryContainer = Color(0xFF6A3C00)
val DarkOnPrimaryContainer = Color(0xFFFFDDB3)
val DarkSecondary = Color(0xFFDEC2A2)
val DarkOnSecondary = Color(0xFF3E2D17)
val DarkSecondaryContainer = Color(0xFF57432B)
val DarkOnSecondaryContainer = Color(0xFFFBDEBC)
val DarkTertiary = Color(0xFFBACD9F)
val DarkOnTertiary = Color(0xFF263514)
val DarkTertiaryContainer = Color(0xFF3C4C28)
val DarkOnTertiaryContainer = Color(0xFFD6E9B9)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF18120C)
val DarkOnBackground = Color(0xFFEEE0D5)
val DarkSurface = Color(0xFF18120C)
val DarkOnSurface = Color(0xFFEEE0D5)
val DarkSurfaceVariant = Color(0xFF50453A)
val DarkOnSurfaceVariant = Color(0xFFD4C4B5)
val DarkOutline = Color(0xFF9D8E81)
